# Build stage
FROM node:lts AS builder
# Set working directory
WORKDIR /build
# Copy application source code
COPY . .
# Install dependencies
RUN npm install
# Build application
RUN npm run build:kube

# Production stage: deploy on nginx
FROM nginx:alpine
# Copy nginx configuration
COPY nginx-kube.conf /etc/nginx/conf.d/default.conf
# Expose port 443
EXPOSE 443
# Copy build files from builder stage into nginx
COPY --from=builder /build/dist/auction-web-app/ /usr/share/nginx/html